import { Injectable, InternalServerErrorException } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { GoogleGenAI, type GenerateContentResponse } from '@google/genai';

@Injectable()
export class AiService {
    private readonly genAI: GoogleGenAI;

    constructor(private readonly configService: ConfigService) {
        const apiKey = this.configService.get<string>('GEMINI_API_KEY');

        if (!apiKey) {
            throw new InternalServerErrorException
                ('GEMINI_API_KEY is not set in the environment variables.');
        }

        this.genAI = new GoogleGenAI({ apiKey });
    }

    async summarizeNews(articles: string[]): Promise<string> {
        try {
            const response: GenerateContentResponse =
                await this.genAI.models.generateContent({
                    model: 'gemini-3.5-flash-lite',
                    contents: `
                Summarize the following news articles into a concise daily briefing.
                Requirements:
                - Group related stories into topics.
                - Explain what happened and why it matters.
                - Avoid repeating the same story.
                - Do not invent facts.
                - Use clear, neutral English.
                - If the articles don't provide enough information, say so.

                News articles:
                ${articles.join('\n\n')}
                `,
                });
            return response.text ?? 'No summary could be generated by the AI.';

        } catch (error: unknown) {
            const message = error instanceof Error ? error.message : String(error);

            if (message.includes('"code":503') ||
                message.includes('"status":"UNAVAILABLE"')) {
                throw new InternalServerErrorException(
                    'Gemini is temporarily overloaded. Please try again shortly.',
                );
            }

            throw new InternalServerErrorException(
                `Failed to summarize news articles: ${message}`,
            );
        }
    }
}
